version: "3.8"
services:
  tinyproxy:
    container_name: tinyproxy
    image: tunnm/tinyproxy:1.11.1
    ports:
      - "8888:8888"
    volumes:
      - ./data:/etc/tinyproxy
    restart: unless-stopped