version: "3.8"
services:
  tinyproxy:
    container_name: tinyproxy
    image: cpfriend1721994/tinyproxy:1.10.0
    ports:
      - "8888:8888"
    volumes:
      - ./data:/etc/tinyproxy
    restart: unless-stopped